name: chatapp

on:
 push:
  branches:
   - main

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build