name: chatapp

on:
 push:
  branches:
   - main

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - name: Install dependencies
        run:  npm install
      - name: Run app
        run : npm expo start  
      - name: Build
        run:  npmrun build