name: chatapp

on:
 push:
  branches:
   - main

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Install bun
        with:
          bun-version: latest
       
          # Install dependencies
      - run: bun install